name: Test Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests with coverage
        run: go test -coverprofile=coverage.out -covermode=atomic ./lib/...

      - name: Build coverage checker tool
        run: |
          cd tools/coverage-check
          go build -o coverage-check
          chmod +x coverage-check

      - name: Check coverage threshold
        run: |
          THRESHOLD=75
          echo "Checking coverage against threshold: $THRESHOLD%"
          ./tools/coverage-check/coverage-check -file coverage.out -threshold $THRESHOLD -verbose
